name: iOS CI

on:
  push:
    branches: [ main, MovieDetailRefactor ]

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List Xcode versions
        run: ls /Applications | grep Xcode

      - name: Select Xcode 15.4
        run: sudo xcode-select -s /Applications/Xcode_15.4.app

      - name: Build app
        run: |
          xcodebuild clean build \
          -project MovieProject.xcodeproj \
          -scheme MovieProject \
          -destination 'generic/platform=iOS Simulator' \
          -sdk iphonesimulator \
          CODE_SIGNING_ALLOWED=NO
