name: iOS CI

on:
  push:
    branches: [ main, MovieDetailRefactor ]
  pull_request:

jobs:
  build:
    runs-on: macos-14

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Show Xcode version
        run: xcodebuild -version

      - name: Build app
        run: xcodebuild clean build \
          -scheme MovieProject \
          -destination 'platform=iOS Simulator,name=iPhone 15'
